apiVersion: v1
data:
  .dockerconfigjson: e30=
kind: Secret
metadata:
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
  creationTimestamp: null
  name: spring-sensors-registry
type: kubernetes.io/dockerconfigjson
